name: Selenify Unit Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:134.0
        options: >-
          --health-cmd="curl --silent --fail localhost:4444/wd/hub/status || exit 1"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=3
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Wait for Selenium container to be ready
        run: |
          until curl --silent --fail localhost:4444/wd/hub/status; do
            echo "Waiting for Selenium container to be ready..."
            sleep 5
          done

      - name: Run Selenium Tests in Docker
        run: |
          docker run --rm \
            --network host \
            -v $(pwd):/app \
            -w /app \
            maven:3.8.4-openjdk-20-slim \
            mvn test -Dselenium.grid.url=http://localhost:4444/wd/hub \
            -Ddriver.chrome.path=/usr/bin/chromedriver
