name: Selenify Unit Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >-
          --health-cmd="curl --silent --fail localhost:4444/wd/hub/status || exit 1"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=3
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Wait for Selenium container to be ready
        run: |
          until curl --silent --fail localhost:4444/wd/hub/status; do
            echo "Waiting for Selenium container to be ready..."
            sleep 5
          done

      - name: Get Chrome Version
        run: |
          # Get Chrome version in the Selenium container
          CHROME_VERSION=$(docker run --rm selenium/standalone-chrome:latest google-chrome --version)
          echo "Chrome version in container: ${CHROME_VERSION}"
          # Extract the major version number
          CHROME_MAJOR_VERSION=$(echo ${CHROME_VERSION} | sed -E 's/.* ([0-9]+)\..*/\1/')
          echo "Chrome major version: ${CHROME_MAJOR_VERSION}"

      - name: Install Matching ChromeDriver
        run: |
          # Install matching ChromeDriver based on the Chrome major version
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION})
          echo "Downloading ChromeDriver version: ${CHROMEDRIVER_VERSION}"
          wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip

      - name: Run Selenium Tests
        run: mvn clean test -Dselenium.grid.url=http://localhost:4444/wd/hub -Ddriver.chrome.path=/usr/local/bin/chromedriver
