name: Selenium Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'maven'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${JAVA_HOME_20_X64}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libgtk-3-dev libnotify-dev libnss3 libxss1

      - name: Kill All Chrome and Chromedriver Processes
        run: |
          sudo pkill -9 -f chrome || true
          sudo pkill -9 -f chromedriver || true

      - name: Set Chrome User Data Directory
        run: echo "TMPDIR=$(mktemp -d)" >> $GITHUB_ENV

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Installing Chrome version: ${CHROME_VERSION}"
          sudo apt-get install -y wget unzip
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Start ChromeDriver in Background
        run: |
          chromedriver --port=9515 --verbose --log-path=chromedriver.log &

      - name: Verify Java & Maven Versions
        run: |
          java -version
          mvn -version

      - name: Run Selenium tests
        run: mvn test -Ddriver.chrome.path=/usr/bin/chromedriver
