name: Selenium Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'maven'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${JAVA_HOME_20_X64}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libgtk-3-dev libnotify-dev libnss3 libxss1

      - name: Run Selenium tests
        run: mvn test -Ddriver.chrome.path=/usr/bin/chromedriver
