name: Selenium Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'maven'

      - name: Install Libraries
        run: |
          sudo apt-get update
          sudo apt install libgtk-3-dev libnotify-dev libnss3 libxss1 libasound2

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo Chrome version is - "${CHROME_VERSION}"
          sudo apt-get install -y wget unzip
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run Selenium tests
        run: mvn test -Ddriver.chrome.path=/usr/bin/chromedriver
